project:
  type: website

website:
  title: "Fundamentals of Computing and Programming"
  page-navigation: true
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

  #   tools:
  #     - icon: github
  #       href:  https://github.com/anandology/isi-fcp

  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href:  https://github.com/anandology/isi-fcp
    contents:
      - index.qmd
      - setup.qmd
      - cmdline.qmd
      - shell.qmd
      - unix-power-tools.qmd
      - git.qmd
      - quarto.qmd
      - section: Problem Sets
        href: problem-sets/index.qmd
        contents:
          - problem-sets/ps1.qmd
      - section: Lecture Notes
        href: lecture-notes/index.qmd
        contents:
          - lecture-notes/01/index.qmd
          - lecture-notes/02/index.qmd
          - lecture-notes/2024-08-12/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



