project:
  type: website
  render:
    - "*.qmd"
    - "*/*.qmd"
    - "*/*.ipynb"

website:
  title: "Fundamentals of Computing and Programming"
  page-navigation: true
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

  #   tools:
  #     - icon: github
  #       href:  https://github.com/anandology/isi-fcp

  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href:  https://github.com/anandology/isi-fcp
    contents:
      - index.qmd
      - setup.qmd
      - cmdline.qmd
      - shell.qmd
      - unix-power-tools.qmd
      - git.qmd
      - quarto.qmd
      - section: Introduction to Python
        contents:
          - python/taste-of-python.qmd
          - python/numpy.ipynb
          - python/plotting.ipynb
      - section: Problem Sets
        href: problem-sets/index.qmd
        contents:
          - problem-sets/ps1.qmd
      - section: Assignments
        href: assignments/index.qmd
        contents:
          - assignments/assignment-02.ipynb
      - section: Lecture Notes
        href: lecture-notes/index.qmd
        contents:
          - lecture-notes/01/index.qmd
          - lecture-notes/02/index.qmd
          - lecture-notes/2024-08-12/index.qmd
          - lecture-notes/2024-09-30/index.qmd
          - lecture-notes/2024-10-14/index.ipynb
          - lecture-notes/2024-10-21/index.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



